name: ExamplePlugin
api: [1.9.0]
version: 1.0
load: POSTWORLD
main: legoburner73\ExamplePlugin\Main
commands:
 test:
  description: "This is a test command"
  permission: ExamplePlugin.user
  
permissions:
 sampleplugin.user:
  description: "Gives access to User commands"
  default: true
